// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsZbewVYIyc7T1IwE_2m0br7ul6ai5DlY',
    appId: '1:731265939482:web:69d5897cab92f4f76fb9a3',
    messagingSenderId: '731265939482',
    projectId: 'chatappproject-70f19',
    authDomain: 'chatappproject-70f19.firebaseapp.com',
    storageBucket: 'chatappproject-70f19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10pkA3EefB903FK5SiG8IRQmoWxykrf4',
    appId: '1:731265939482:android:d4b416d1a9acdf276fb9a3',
    messagingSenderId: '731265939482',
    projectId: 'chatappproject-70f19',
    storageBucket: 'chatappproject-70f19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1iFW08AogITAm3oUW_glJK-34lIhDuzs',
    appId: '1:731265939482:ios:9a939215796cbd946fb9a3',
    messagingSenderId: '731265939482',
    projectId: 'chatappproject-70f19',
    storageBucket: 'chatappproject-70f19.appspot.com',
    iosBundleId: 'com.chatappflutter.chatappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1iFW08AogITAm3oUW_glJK-34lIhDuzs',
    appId: '1:731265939482:ios:ddc629b822df3a906fb9a3',
    messagingSenderId: '731265939482',
    projectId: 'chatappproject-70f19',
    storageBucket: 'chatappproject-70f19.appspot.com',
    iosBundleId: 'com.chatappflutter.chatappflutter.RunnerTests',
  );
}
